<?php /* Smarty version 2.6.29, created on 2016-06-04 03:32:44
         compiled from res_logflags.tpl */ ?>
<?php if ($this->_tpl_vars['lfSpace'] && ( $this->_tpl_vars['logItem']['needs_maintenance'] == 2 || ( $this->_tpl_vars['logItem']['needs_maintenance'] == 1 && ! ( isset ( $this->_tpl_vars['logItem']['type'] ) && $this->_tpl_vars['logItem']['type'] == 10 ) ) || $this->_tpl_vars['logItem']['listing_outdated'] == 2 || ( $this->_tpl_vars['logItem']['listing_outdated'] == 1 && ! ( isset ( $this->_tpl_vars['logItem']['type'] ) && $this->_tpl_vars['logItem']['type'] == 10 ) ) || ( $this->_tpl_vars['withRecommendation'] && $this->_tpl_vars['logItem']['recommended'] ) )): ?>&nbsp;<?php endif; ?>
<?php if ($this->_tpl_vars['logItem']['needs_maintenance'] == 2): ?><img src="resource2/<?php echo $this->_tpl_vars['opt']['template']['style']; ?>
/images/log/16x16-needs-maintenance.png" alt="Der Cache benötigt Wartung." title="Der Cache benötigt Wartung." /><?php if ($this->_tpl_vars['logItem']['listing_outdated']): ?>&nbsp;<?php endif; ?><?php elseif ($this->_tpl_vars['logItem']['needs_maintenance'] == 1 && ! ( isset ( $this->_tpl_vars['logItem']['type'] ) && $this->_tpl_vars['logItem']['type'] == 10 )): ?><img src="resource2/<?php echo $this->_tpl_vars['opt']['template']['style']; ?>
/images/log/16x16-needs-maintenance-no.png" alt="Der Cache ist in gutem oder akzeptablem Zustand." title="Der Cache ist in gutem oder akzeptablem Zustand." /><?php if ($this->_tpl_vars['logItem']['listing_outdated']): ?>&nbsp;<?php endif; ?><?php endif; ?>
<?php if ($this->_tpl_vars['logItem']['listing_outdated'] == 2): ?><img src="resource2/<?php echo $this->_tpl_vars['opt']['template']['style']; ?>
/images/log/16x16-listing-outdated.png" alt="Die Cachebeschreibung ist veraltet." title="Die Cachebeschreibung ist veraltet." /><?php elseif ($this->_tpl_vars['logItem']['listing_outdated'] == 1 && ! ( isset ( $this->_tpl_vars['logItem']['type'] ) && $this->_tpl_vars['logItem']['type'] == 10 )): ?><img src="resource2/<?php echo $this->_tpl_vars['opt']['template']['style']; ?>
/images/log/16x16-listing-outdated-no.png" alt="Die Cachebeschreibung ist in Ordnung." title="Die Cachebeschreibung ist in Ordnung." /><?php endif; ?>
<?php if ($this->_tpl_vars['withRecommendation'] && $this->_tpl_vars['logItem']['recommended'] == 1): ?>  <img src="images/rating-star.gif" border="0" alt="Empfohlen" width="17px" height="16px" /><?php endif; ?>